### ISSUE TITLE
[enhancement] CLI development

### ISSUE THREAD

**Issue by ukkopahis** [SensorsIot/IOTstack#505]
I'm working on a CLI interface and a proper backend for stack modification and maintenance.

## Tasks:
- [x] use python virtualenv to avoid polluting or conflicting with python libraries on the host
- [ ] fix conflicting ports - all services can be installed at the same time using their default configuration.
- [ ] change node-red image to install addons on startup based on environment variables (not to have addon selection built-in into the base image)
- [ ] eliminate need for template specific python code by supporting replaceable variables in service.yml
- [ ] update menu to also use the same backing python code for building the stack.
- [ ] add github hook/actions to run python tests&linting and to run template validity checks (for all commits and pull-requests)

## Planned CLI (will surely still change):
```
usage: build.sh [-h] (-L | -R | -U | -D | -C) [-v] [-n]
                [-a KEY=VALUE [KEY=VALUE ...]] [-p PASSWORD]
                [CONTAINER_NAME ...]

positional arguments:
  CONTAINER_NAME        Containers to add, update or remove, depending on the
                        selected operation. Unlisted containers are kept
                        unmodified. Use the special value "CURRENT" to apply
                        operation for all added containers.

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Print extra information to stderr. Use twice for debug
                        information.
  -n, --no-backup       Don't create backup before writing changes. Default is
                        to create backup named "docker-
                        compose.yml.`DATETIME`.bak".
  -a KEY=VALUE [KEY=VALUE ...], --assign KEY=VALUE [KEY=VALUE ...]
                        Add variable assignment to set when adding or updating
                        containers e.g. "pihole.ports.80/tcp=1080". When
                        updating, variables default to already previous values
                        read from your current stack file (docker-
                        compose.yml).
  -p PASSWORD, --default-password PASSWORD
                        Use PASSWORD for all containers instead of creating
                        new random passwords. To update already existing
                        containers use the --recreate flag. Note: some
                        containers will store passwords into their own
                        databases, to change such passwords see the
                        container's documentation.

Operation, use exactly one:
  -L, --list            Print out current containers in the stack and their
                        passwords
  -R, --recreate        Add or recreate listed container definitions. Will
                        overwrite any custom modifications you may have made,
                        but preserves previous passwords.
  -U, --update          Add or update listed container definitions. Preserves
                        previous variable assignments, generated passwords and
                        manual customizations. In certain corner-cases this
                        will result in an invalid configuration. Use
                        --recreate to correct in such a case.
  -D, --delete          Remove listed containers from the stack.
  -C, --check           Check all templates for port conflicts and exit. Use
                        during container template development.

Examples:
    List all available containers:
        build.sh --list

    Add pihole and wireguard services:
        build.sh --update -p secret_password pihole wireguard

    To update current service definitions after a "git pull":
        build.sh --recreate CURRENT
```
